apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image:  api-produtos
      docker:
        dockerfile: Dockerfile
  local: {}

deploy:
  kubectl:
    manifests:
      - config.yaml
      - deploy.yaml